name: Deploy to GitHub Pages on merge
"on":
  push:
    branches:
      - live
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - run: pnpm install --no-frozen-lockfile
      - name: Deploy using bot
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          pnpm gh-pages-actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
